#!/bin/sh
set -e
echo "Stopping cr4shedd..."
launchctl unload /var/jb/Library/LaunchDaemons/com.muirey03.cr4shedd.plist 2>/dev/null || true
killall -9 cr4shedd 2>/dev/null || true
echo "Killing ReportCrash..."
killall -9 ReportCrash 2>/dev/null || true
echo "Killing ReportMemoryException..."
killall -9 ReportMemoryException 2>/dev/null || true
chown root:wheel /var/jb/usr/libexec/cr4shedd
chmod 0755 /var/jb/usr/libexec/cr4shedd
chown root:wheel /var/jb/Library/LaunchDaemons/com.muirey03.cr4shedd.plist
chmod 644 /var/jb/Library/LaunchDaemons/com.muirey03.cr4shedd.plist
echo "Starting cr4shedd..."
launchctl load /var/jb/Library/LaunchDaemons/com.muirey03.cr4shedd.plist 2>/dev/null || true
echo "Done!"
exit 0
